### ISSUE TITLE
dvdisaster produces GBs of stdout during repair = enormous performance penalty, can repair >4x faster without the logging

### ISSUE THREAD

**Issue by jjr90** [speed47/dvdisaster#100]
stdio is very [expensive](https://stackoverflow.com/a/1832503), not to mention the string formatting. This is known to anyone who profiles high-performance C software.

RS03, SL BD, with ~5% redundancy and ~4% corruption produces **1 GB** of stdout (_counting the `\b` backspaces_) -- due to the mandatory repair logging in `rs03-fix.c`. That's a huge mandatory penalty for the average user.

* Baseline (terminal): All repair logging left as-is in `rs03-fix.c`, Ubuntu terminal: progress **0.7% in 60 seconds**.
* Baseline (file): All repair logging left as-is in `rs03-fix.c`, redirect to file: progress **1.0% in 60 seconds**.
* Improvement: All repair logging **disabled** in `rs03-fix.c`, Ubuntu terminal: progress **3.9% in 60 seconds**.

These results were reproducible with individually-randomized test cases.

**For 20% corruption** with the recommended 20% redundancy, the repair logs would be 4x denser for the same image size, resulting in a 4x worse penalty, I'd expect.

I measured the above using the `timeout` command and then finding last-occurring progress % line in the file or terminal.

In order to do that for the terminal cases, I had to change your progress % lines from the old-fashioned and impossible-to-grep `'\b' x line length` to the more-common single `'\r'`, which allows piping through `tr '\r' '\n'` to grep the Ecc progress reports. My shell was just erasing the progress lines in the pipe somehow, otherwise.

But you can use the file redirect to test this without changing that code.

**Comment by jjr90** [comment]
Please feel free to change the title to something shorter. I wanted to summarize the content, in case maintainers aren't having much time to look at issues.

**Comment by speed47** [comment]
I noticed that too, and I was suspecting that it was probably slowing down the process, but I didn't actually took the time to bench it as you did, thanks.

To be honest, I feel that the following snippet:
https://github.com/speed47/dvdisaster/blob/aa9065f0c0ab8f68de936372d6b956a8cf9d3f4b/src/rs03-fix.c#L737-L764
was useful to the original author to test his code, as the whole block's goal is just to `printf` the lines you're referring to, which are not really meaningful or interesting for the users. As per your timings, it seems clear that nullifying this block except in debug mode would be the best course of action, for a hefty 4x repair perf gain. I'll push a branch with this change.

**Comment by speed47** [comment]
This output is also used during the non-regression tests, but the code I've pushed keeps this block active under both regtests and debug mode, which should be sufficient.

**Comment by jjr90** [comment]
> nullifying this block except in debug mode

There was an `error_count++` in there that gets propagated through to the Verbose summary at the end of the function, though (`damaged_eccsecs`). So maybe something more granular. I was just going to change the PrintCLIs to Verbose, but you're right, nobody wants to see byte logs.

**Comment by jjr90** [comment]
> There was an `error_count++` in there that gets propagated through to the Verbose summary

Oh, it may be worse than that. A condition on its derived `erasure_count` is also controlling a [LargeWrite back into the image ](https://github.com/speed47/dvdisaster/blob/aa9065f0c0ab8f68de936372d6b956a8cf9d3f4b/src/rs03-fix.c#L827).

**Comment by speed47** [comment]
Indeed, catched that too while the regtests were running, I've modified the code a bit to only print the "bytelog" in regtests OR (debug and verbose) modes, "debug" being, in dvdisaster language, "using `--debug` which unlocks dangerous/undocumented command-line options", so that regular `--verbose` users are not impacted.

Thanks for your vigilance though, it's nice to have additional eyes when patching such code.

**Comment by jjr90** [comment]
FYI there are some straggler PrintCLIs in the function that are still emitting useless output. I just I remembered I had to remove some more than what you removed to make it _visually clean_. (Not sure of the performance impact of what's left... it might just be cosmetic... up to you. nntr)
