### ISSUE TITLE
AppImage issue

### ISSUE THREAD

**Issue by anarchomoh** [speed47/dvdisaster#60]
Hi, I am getting an error when trying to run the app image:

/tmp/.mount_dvdisaGUl8Qd/usr/bin/dvdisaster: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

Can you help please?

**Comment by speed47** [comment]
What is your Linux distro and version?

**Comment by anarchomoh** [comment]
Thanks for replying. I use Void Linux - it is rolling release.

**Comment by speed47** [comment]
Interesting, never tried this distro, but theoretically AppImages should work everywhere, as all binaries and libraries dependencies are self-contained there and don't make too many assumptions about the host OS libs. 
I think I'll have to try to reproduce the problem in a VM with Void Linux installed.

**Comment by anarchomoh** [comment]
Thanks for trying, yes that's why I tried the AppImage.

**Comment by speed47** [comment]
It seems to be a known bug on AppImage builder https://github.com/AppImage/AppImageKit/issues/1162
Implementing a workaround right now

**Comment by speed47** [comment]
Can you try with the latest AppImage? I regenerated it implementing the workaround cited in the bug report above

**Comment by anarchomoh** [comment]
That update fixed the issue! Thanks Heaps!

**Comment by speed47** [comment]
Glad to hear it works, thanks for reporting!
