### ISSUE TITLE
Embedding RS03 ECC in image with memory-mapped IO fails direct verification, generates CRC errors

### ISSUE THREAD

**Issue by marhry** [speed47/dvdisaster#82]
OS: Windows 10
Version: v0.79.10-pl2

Settings:
![grafik](https://github.com/speed47/dvdisaster/assets/5941638/7bc1646d-482d-4c27-b096-d8bc3589fca2)

With these settings, dvdisaster-enhanced .iso files consistently fail the "Verify" step before burning to disk on my end. I originally noticed this after burning a full BDXL and trying to verify the re-read iso and narrowed it down a bit.

To reproduce:
1) Create a small image .iso (I had about 170 MB with various files) 
2) Use above settings to embed ECC info
3) Run "Verify" on this new image immediately. The result in my case was:
![grafik](https://github.com/speed47/dvdisaster/assets/5941638/85b7924c-7060-47e1-875c-a38308423fb7)

Workaround:
Set I/O method to read/write again

**Comment by michilumin** [comment]
Also showing this exact issue with separate-file ecc, so it seems to be generating bad ECC data when I/O is set to memory-mapped, no matter what the method or target.

In my case this is also on BDXL media, 100 and 128gb.  (Have not verified the issue yet on DVD/BD SL-DL media.)

BDXL 128GB separate-file ECC data written with memory-mapped I/O then verified: 
(note fingerprint match and sector count match to below R/W file.) 
(Also shows Data Checksum at beginning of verify, when R/W I/O does not.)

![image](https://github.com/speed47/dvdisaster/assets/6802127/50840af0-be04-4ae6-b005-9322cd8b9ec7)


BDXL 128GB separate-file ECC data written with Read/Write I/O and then verified:  (deep verification aborted)
(No Data Checksum displayed, however all sectors verify good.) 

![image](https://github.com/speed47/dvdisaster/assets/6802127/2dba3bb2-bd61-4288-b605-cc0ae1b0d7c4)

Just finding it odd that we get a data checksum on the 'bad file', created with mmap-i/o, whereas we do not on the 'good file' created with r/w io. 

File sizes of the "good" (R/W I/O) and "bad" (mmap I/O) .ecc files are identical.

Looking inside the .ecc files, i'm seeing an alternating pattern of "blocks" of data that are completely different but then returning to completely identical. I'm not sure if that helps much if any, but wanted to see if maybe it was something simple like an offset (it isn't.)

**Comment by speed47** [comment]
Thanks for the detailed report!

I can't reproduce the problem with the Linux build, nor the Windows 32 bits build, but I confirm I can reproduce it with the 64 bits build. The number of threads doesn't change anything, so it's not a thread-synchronization problem. It seems to be a 32 vs 64 bits issue, but only applicable to Windows.

**Comment by speed47** [comment]
Found the problem, in fact memory-mapped i/o has never been supported in the program under other OSes than Linux, but an error in the code implies that if mmap is selected under Windows, even if the program correctly fallsback to normal i/o, a portion of code that needs to be ran under normal i/o but not mmaped-i/o is NOT executed where it should be, which corrupts the data.

Fix incoming
