### ISSUE TITLE
Fix Appimage Icon

### ISSUE THREAD

**Issue by harrypm** [speed47/dvdisaster#84]
Minnor issue, but the app image icon wont present on taskbars etc with Linux Mint for example.

If the icon file could be posted here to manaully overide It would be apprachated as [this](https://itsfoss.community/t/programs-in-appimage-format-do-not-show-program-icons/5387/4) is the only possible work around I've found so far.

**Comment by speed47** [comment]
The icon is available here: https://github.com/speed47/dvdisaster/blob/master/contrib/dvdisaster64.png
