### ISSUE TITLE
macOS Build not Opening 

### ISSUE THREAD

**Issue by dejl** [speed47/dvdisaster#85]
Hi

I have latest macOS Sonoma 14.3 (Apple M1)
The macOS build doesn't open. I have also tried the CLionly build, same message
<img width="372" alt="Screenshot 2024-02-02 at 6 07 55 pm" src="https://github.com/speed47/dvdisaster/assets/251785/7e74bbb2-2b66-4606-a35d-5be01d17a3fc">

I have also tried launching the executable in the macOS folder of the .app, and the same message.

**Comment by albertogarciacz** [comment]
I have the same problem. Running on Sonoma 14.3, M2 MAX.

**Comment by vicmarto** [comment]
Same here (Sonoma 14.3 on an INTEL mac).

**Comment by speed47** [comment]
Hello,

Unfortunately I don't have a Mac, so I'm pretty blind about the MacOS build. The only thing I have is the automated regression tests on GitHub (which do pass), and I also use GitHub actions to build the Mac version and package it.

I suspect this might be an issue with the dmg packaging, as the binary does work in the regression tests launched by GitHub on a Mac, using macOS 12. Could one of you unpack the dmg file and try to launch the binary manually?

I see that GitHub now supports macOS 13 and 14 in beta, so I could also try to build under those, but I suspect/hope that an app built for macOS 12 is also supposed to work on a more recent version?

**Comment by albertogarciacz** [comment]
I mounted the dmg and ten ran /Volumes/dvdisaster-v0.79.10-pl2-cli-only/dvdisaster.app/Contents/MacOS/dvdisaster from the command line. Unfortunately resulting in the same error message.

**Comment by dejl** [comment]
The latest release is the same as above as well


I cloned the repo and can get a working build from source without any fuss, though.

<img width="1440" alt="Screenshot 2024-02-22 at 11 40 39 pm" src="https://github.com/speed47/dvdisaster/assets/251785/5d1b89c3-5681-4705-8a9c-69fac2fb0e9a">

**Comment by vwellum** [comment]
When sht like this happens:
`sudo xattr -cr /Applications/dvdisaster.app` 
usually fixes most of the things.

**Comment by speed47** [comment]
> When sht like this happens: `sudo xattr -cr /Applications/dvdisaster.app` usually fixes most of the things.

Oh, is that because macOS tags the file as being downloaded from Internet and somehow insecure, or something like that?
If this fixes the problem, can somebody run `xattr -lr /Applications/dvdisaster.app` before, so that I can get an idea of which extended attributes are causing this behavior?

**Comment by albertogarciacz** [comment]
I've just run `sudo xattr -c /Applications/dvdisaster.app` and then the app and it seems to solve the problem described. 
<img width="892" alt="Screenshot 2024-03-11 at 17 04 11" src="https://github.com/speed47/dvdisaster/assets/20310380/e2d4194f-d41c-4fe8-960b-68414ce3719c">

Please find output of `sudo xattr -l /Applications/dvdisaster.app` that I had ran beforehand. 
`com.apple.provenance:
0000   01 00 00 71 6A 30 22 ED C8 C3 53                   ...qj0"...S

com.apple.quarantine: 0183;65ef2a9f;Safari;1E4929C3-C9A7-461B-BE3F-4E5D8CB1E8FF`

**Comment by speed47** [comment]
Thanks a lot for the feedback. A lot of resources can be found online about this ``com.apple.quarantine`` attribute behavior, which seems to be set when a program is downloaded from anywhere except the Apple store. The error message is extremely misleading, I have no idea why they didn't go the "**warning: this program has been downloaded from an unknown source, please run it only if you completely trust the source**" instead, but, well, that's how it is.

I've added the information on the release page and referenced this issue. Thanks!
